# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt6 UI code generator 6.6.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lable_top = QtWidgets.QLabel(parent=self.centralwidget)
        self.lable_top.setEnabled(True)
        self.lable_top.setGeometry(QtCore.QRect(150, 30, 300, 31))
        self.lable_top.setMinimumSize(QtCore.QSize(0, 0))
        self.lable_top.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lable_top.setFont(font)
        self.lable_top.setText("")
        self.lable_top.setObjectName("lable_top")
        self.label_top = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_top.setGeometry(QtCore.QRect(220, 30, 241, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_top.setFont(font)
        self.label_top.setObjectName("label_top")
        self.label_school_year = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_school_year.setGeometry(QtCore.QRect(80, 130, 121, 20))
        self.label_school_year.setObjectName("label_school_year")
        self.label_first_name = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_first_name.setGeometry(QtCore.QRect(80, 70, 71, 16))
        self.label_first_name.setObjectName("label_first_name")
        self.label_last_name = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_last_name.setGeometry(QtCore.QRect(80, 100, 91, 16))
        self.label_last_name.setObjectName("label_last_name")
        self.label_midterm = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_midterm.setGeometry(QtCore.QRect(80, 160, 91, 16))
        self.label_midterm.setObjectName("label_midterm")
        self.label_final = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_final.setGeometry(QtCore.QRect(80, 190, 111, 16))
        self.label_final.setObjectName("label_final")
        self.line_first_name = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.line_first_name.setGeometry(QtCore.QRect(230, 70, 161, 21))
        self.line_first_name.setObjectName("line_first_name")
        self.line_last_name = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.line_last_name.setGeometry(QtCore.QRect(230, 100, 161, 21))
        self.line_last_name.setObjectName("line_last_name")
        self.radioButton_freshman = QtWidgets.QRadioButton(parent=self.centralwidget)
        self.radioButton_freshman.setGeometry(QtCore.QRect(230, 130, 100, 20))
        self.radioButton_freshman.setObjectName("radioButton_freshman")
        self.radioButton_sophmore = QtWidgets.QRadioButton(parent=self.centralwidget)
        self.radioButton_sophmore.setGeometry(QtCore.QRect(340, 130, 100, 20))
        self.radioButton_sophmore.setObjectName("radioButton_sophmore")
        self.radioButton_junior = QtWidgets.QRadioButton(parent=self.centralwidget)
        self.radioButton_junior.setGeometry(QtCore.QRect(460, 130, 100, 20))
        self.radioButton_junior.setObjectName("radioButton_junior")
        self.radioButton_senior = QtWidgets.QRadioButton(parent=self.centralwidget)
        self.radioButton_senior.setGeometry(QtCore.QRect(570, 130, 100, 20))
        self.radioButton_senior.setObjectName("radioButton_senior")
        self.lineEdit_3 = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEdit_3.setGeometry(QtCore.QRect(230, 160, 113, 21))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.lineEdit_4 = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEdit_4.setGeometry(QtCore.QRect(230, 190, 113, 21))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.pushButton_student_info = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_student_info.setGeometry(QtCore.QRect(230, 230, 161, 32))
        self.pushButton_student_info.setObjectName("pushButton_student_info")
        self.pushButton_final = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_final.setGeometry(QtCore.QRect(460, 310, 181, 61))
        self.pushButton_final.setObjectName("pushButton_final")
        self.text_warning = QtWidgets.QTextBrowser(parent=self.centralwidget)
        self.text_warning.setGeometry(QtCore.QRect(80, 320, 331, 51))
        self.text_warning.setObjectName("text_warning")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 24))
        self.menubar.setObjectName("menubar")
        self.menuGPA = QtWidgets.QMenu(parent=self.menubar)
        self.menuGPA.setObjectName("menuGPA")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuGPA.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "GPA"))
        self.label_top.setText(_translate("MainWindow", "GRADE and GPA calculator"))
        self.label_school_year.setText(_translate("MainWindow", "School Year"))
        self.label_first_name.setText(_translate("MainWindow", "First Name"))
        self.label_last_name.setText(_translate("MainWindow", "Last Name"))
        self.label_midterm.setText(_translate("MainWindow", "Midterm Score"))
        self.label_final.setText(_translate("MainWindow", "Final Exam Score"))
        self.radioButton_freshman.setText(_translate("MainWindow", "Freshman"))
        self.radioButton_sophmore.setText(_translate("MainWindow", "Sophmore"))
        self.radioButton_junior.setText(_translate("MainWindow", "Junior"))
        self.radioButton_senior.setText(_translate("MainWindow", "Senior"))
        self.pushButton_student_info.setText(_translate("MainWindow", "Submit (Student Info)"))
        self.pushButton_final.setText(_translate("MainWindow", "Final Report"))
        self.text_warning.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'.AppleSystemUIFont\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Click &quot;Final Report after completing submitting all infomration for each student&quot;</p></body></html>"))
        self.menuGPA.setTitle(_translate("MainWindow", "GPA"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
